### get without authorization
GET http://localhost:3003/api/blogs

### this is using ivan's token
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImN3aml2YW4iLCJpZCI6IjY3ZGMyN2JlMTBkYjc0ODAyOWFmY2Q3YSIsImlhdCI6MTc0MjQ4MTUwMn0.joLGclFDqf50MgswzoZ4ck7P2tBBAx3ovIREtnrWn6o

{
    "title": "we should legalize nuclear bombs",
    "url": "hawk.coinbase.com",
    "likes": 42069
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inlhbmd6aXppIiwiaWQiOiI2N2I4NzAxODhhZTA4ZWExMzFlYzQ3ZjgiLCJpYXQiOjE3NDAxNDY4MjV9.Ohpouej9bLT0XRqGV8zpwnO3NxWDWiS6e3IzMkiVaZw

{
    "title": "zee zee post",
    "url": "cheem.com",
    "likes": 42069
}

### 
PUT http://localhost:3003/api/blogs/6774d8d5308c0645bf8df5ff
Content-Type: application/json

{
    "title": "no hawk tuah",
    "url": "nope.com",
    "author": "falcon"
}

### No token auth, POST rejected
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "No doy",
    "author": "cheems",
    "url": "cheems.com",
    "likes": 42069
}