POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "cwjivan",
    "password": "chan"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "yangzizi",
    "password": "iheartdai"
}